language: node_js

node_js:
  - 6

env:
  global:
    - GH_REF: github.com/vaeum/vseopro.git
    - secure: JV9dBJlhUxfhggFHZ1IvhIAiNr/9W9Y1PcYDcW2ayC3v7m4EPimIn5CrBV94sZvxfub20MQKXxsbLTTFY2GOUVg9TIyguyyHNzZEFeigIjOJF35YmAZ+CgITC6pBGf2uwjDzbZouwD9erQf5z1mzjxLn4dpDjumlfu0io1Ri45wG32SjZdJfV6oaFOHf8SHQdcC9P/bNV+3lHdzNrfPtrJO0g/aq+5MqCUSJiaJfT5px8ZjW/zk40QWtVoydhQJmbJhE04zme0etx+vt9S5G0Q7mEItO64J3IsdPJFXMFWLiUv29Jm/mxsGNzA4YSLcd7h5F9h4j7JPccJ0rA6PoiXBotBwxQCXedg2jJX9cmEX0qogR0uHyVRjy5ZdeNN445jPkQX5uNjCYBNRc9nHDBOz8ouT8KZ/FHKgZbGsk8I9F2ZXNQnwl66YAJ/wS+MGdFfFDxL20lMSevOXy2XdnzHVYdyrQ46Ua34QPpX4Nc/op09M24T04bxz8tED2Ge+Bt/ehnDkbPIBsomBYtpIvB4LkArGix7+Wq6hnhxaMl89HrJ5RTWqzE8BiX7nPwYpLxT22RmVbvDdo8Ir91tIzgpESmtZPTmE6RqYsMDbexQmmRpaJN5IuRK1n9ruNbI+ib6MgNgaDITmfPm4pEuYLUaEGRR+z7tO1qIM7KG/7P2k=

before_install:
- npm config set depth 0
- npm install -g babel-cli

before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - npm install

script:
  - make build
  - cd app
  - git init
  - git config user.name "Alexander Anpleenko"
  - git config user.email "vaeum@yahoo.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

